[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib', '../node_modules' ]
test = 'test'
cache_path  = 'cache_forge'
auto_detect_remappings = true # recursive auto-detection of remappings

# Default optimizer settings
optimizer = true
optimizer_runs = 200

[profile.release]
# Release profile settings (usually used for optimized builds)
optimizer = true
optimizer_runs = 200

[solc]
allow_paths = "../node_modules"

[profile.solidity]
# Specify different compiler versions for different contracts
"0.7.6" = { path = ".", optimizer = true, optimizer_runs = 200, allow_paths = "*", overwrite = "..=.." }
"0.4.18" = { path = ".", evm_version = "byzantium", optimizer = true, optimizer_runs = 200, allow_paths = "*" }

[profile.overrides]
# Override settings for specific contracts
"src/WETH9.sol" = { version = "0.4.18", evm_version = "byzantium", optimizer = true, optimizer_runs = 200, allow_paths = "*" }


